<?php

# Erase the except more end
add_filter( 'excerpt_more', 'wmb_excerpt_more' ) ;
function wmb_excerpt_more( $more ) {
	return '';
}

# Modify the length of the autogenerated excerpt
add_filter( 'excerpt_length', 'wmb_excerpt_length' ) ;
function wmb_excerpt_length( $more ) {
	return 100;
}

# Length of the autogenerated excerpt for the main slider
function wmb_excerpt_length_slider( $more ) {
	return 74;
}

# Add a "Read More" link to the end of each excerpt
add_filter( 'the_excerpt', 'wmb_the_excerpt' );
function wmb_the_excerpt( $excerpt ) {
	$maxlength = 400;
	
	$excerpt = strip_tags( $excerpt );
	$excerpt = strlen( $excerpt ) > $maxlength ? substr( $excerpt, 0, $maxlength ) : $excerpt;
	$excerpt = wpautop( $excerpt );

	$link = '<a href="' . esc_url( get_permalink() ) . '">' . esc_html__( 'Read more', 'crb' ) . '</a>';
	$excerpt = preg_replace( '~(</p>)$~', '... ' . $link . '$1', $excerpt );
	
	return $excerpt;
}